// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQy0_FCvg4ZqYorhlT_27KEaiCb_ESTI0',
    appId: '1:765538409473:web:6dad9119c5785d952df400',
    messagingSenderId: '765538409473',
    projectId: 'pythonlearning-8afa3',
    authDomain: 'pythonlearning-8afa3.firebaseapp.com',
    storageBucket: 'pythonlearning-8afa3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oNft_vrhwptOJU6ppqSMb6ASePaAr5M',
    appId: '1:765538409473:android:2386e69c6f5a830c2df400',
    messagingSenderId: '765538409473',
    projectId: 'pythonlearning-8afa3',
    storageBucket: 'pythonlearning-8afa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpMaZYVlJBCzRxPP58pQj0pMXAEcSBPTs',
    appId: '1:765538409473:ios:71c1f3a7706507482df400',
    messagingSenderId: '765538409473',
    projectId: 'pythonlearning-8afa3',
    storageBucket: 'pythonlearning-8afa3.firebasestorage.app',
    iosBundleId: 'com.example.learnpythonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpMaZYVlJBCzRxPP58pQj0pMXAEcSBPTs',
    appId: '1:765538409473:ios:71c1f3a7706507482df400',
    messagingSenderId: '765538409473',
    projectId: 'pythonlearning-8afa3',
    storageBucket: 'pythonlearning-8afa3.firebasestorage.app',
    iosBundleId: 'com.example.learnpythonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQy0_FCvg4ZqYorhlT_27KEaiCb_ESTI0',
    appId: '1:765538409473:web:17d2a97db30727d72df400',
    messagingSenderId: '765538409473',
    projectId: 'pythonlearning-8afa3',
    authDomain: 'pythonlearning-8afa3.firebaseapp.com',
    storageBucket: 'pythonlearning-8afa3.firebasestorage.app',
  );
}
